# Очистка данных




Загружаем данные на виртуалку

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sales.csv to sales.csv

In [ ]:
# импортируем библиотеки 
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## Очистка данных: Ticket Sales Data
Набор данных выглядит совсем не очень. В нём есть пропущенные значения, избыточная, и не предназначенная для анализа информация. Задача: Привести набор данных в приличный вид. Сделать так, чтобы на этот набор данных было приятно смотреть, и было легко строить на основе него дальнейшую аналитику.

In [ ]:
df=pd.read_csv('sales.csv', encoding= 'latin1', index_col=0)
df

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
1     abcaf1adb99a935fc661  43f0436b905bfa7c2eec  ...           NaN         NaN
2     6c56d7f08c95f2aa453c  1a3e9aecd0617706a794  ...           NaN        59.0
3     c7ab4524a121f9d687d2  4b677c3f5bec71eec8d1  ...           NaN         NaN
4     394cb493f893be9b9ed1  b1ccea01ad6ef8522796  ...           NaN         NaN
5     55b5f67e618557929f48  91c03a34b562436efa3c  ...           NaN         NaN
...                    ...                   ...  ...           ...         ...
4996  79372bc1e7e14dfd3f82  a14232befff04be1e2f3  ...           NaN         NaN
4997  f3b0de6a19e2a16e4fb1  83e5715f0ed3e13e6398  ...           NaN         NaN
4998  7c9e2f6847a2dbe4ebff  9ea8ab40f58d18305ac8  ...           NaN         5.0
4999  7af1ccd9a3ec3b6cef1c  e274b5c11a2a63e00141  ...           NaN         NaN
5000  802f4bf8026e38c2acf2  24c326bd80bd2c8c9e17  ...           NaN         NaN

[5000 rows x 45 columns]

In [ ]:
df.sample(n=4)

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
251   6756f0aa1aa31fa36b2e  db87ece23f7dc5c4d6b5  ...           NaN         NaN
559   ee8960babf8ecbc0deac  03cabca4db63531dc982  ...           NaN         7.0
2516  c2e6e876725dd5ea3d64  ac4b847b3fde66f2117e  ...           NaN         NaN
4526  84b8088ac98fd6ad7a8d  75578de54ddf5b3ca7dd  ...           NaN         NaN

[4 rows x 45 columns]

Из набора можно выделить следующие данные


1.   event_id
2.   primary_act_id
3.   primary_act_id	
4.   secondary_act_id	
5.   purch_party_lkup_id	
6.   event_name	
7.   primary_act_name	
8.   secondary_act_name	
9.   major_cat_name	
10.  minor_cat_name	
11.  la_event_type_cat	
12.  event_disp_name	
13.  ticket_text	
14.  tickets_purchased_qty	
15.  trans_face_val_amt	
16.  delivery_type_cd	
17.  event_date_time	
18.  event_dt		
19.  onsale_dt	
20.  sales_ord_create_dttm	
21.  sales_ord_tran_dt	
22.  print_dt	
23.  timezn_nm	
24.  venue_city	
25.  venue_state	
26.  venue_postal_cd_sgmt_1	
27.  print_flg	
28.  la_valid_tkt_event_flg	
29.  fin_mkt_nm		
30.  gndr_cd	age_yr	
31.  income_amt	
32.  edu_val	
33.  edu_1st_indv_val	
34.  edu_2nd_indv_val	
35.  adults_in_hh_num	
36.  married_ind	
37.  child_present_ind	
38.  ome_owner_ind	
39.  occpn_val	
40.  occpn_1st_val	
41.  occpn_2nd_val	
42.  dist_to_ven
43.  presale_dt
44.  sales_platform_cd	
45.  web_session_cookie_val

In [ ]:
df.columns

Index(['event_id', 'primary_act_id', 'secondary_act_id', 'purch_party_lkup_id',
       'event_name', 'primary_act_name', 'secondary_act_name',
       'major_cat_name', 'minor_cat_name', 'la_event_type_cat',
       'event_disp_name', 'ticket_text', 'tickets_purchased_qty',
       'trans_face_val_amt', 'delivery_type_cd', 'event_date_time', 'event_dt',
       'presale_dt', 'onsale_dt', 'sales_ord_create_dttm', 'sales_ord_tran_dt',
       'print_dt', 'timezn_nm', 'venue_city', 'venue_state',
       'venue_postal_cd_sgmt_1', 'sales_platform_cd', 'print_flg',
       'la_valid_tkt_event_flg', 'fin_mkt_nm', 'web_session_cookie_val',
       'gndr_cd', 'age_yr', 'income_amt', 'edu_val', 'edu_1st_indv_val',
       'edu_2nd_indv_val', 'adults_in_hh_num', 'married_ind',
       'child_present_ind', 'home_owner_ind', 'occpn_val', 'occpn_1st_val',
       'occpn_2nd_val', 'dist_to_ven'],
      dtype='object')

Находим и удаляем дубликаты

In [ ]:
new_df = df.T.drop_duplicates().T

Был удален web_session_cookie_val, так как он дублировал purch_party_lkup_id

In [ ]:
new_df.columns

Index(['event_id', 'primary_act_id', 'secondary_act_id', 'purch_party_lkup_id',
       'event_name', 'primary_act_name', 'secondary_act_name',
       'major_cat_name', 'minor_cat_name', 'la_event_type_cat',
       'event_disp_name', 'ticket_text', 'tickets_purchased_qty',
       'trans_face_val_amt', 'delivery_type_cd', 'event_date_time', 'event_dt',
       'presale_dt', 'onsale_dt', 'sales_ord_create_dttm', 'sales_ord_tran_dt',
       'print_dt', 'timezn_nm', 'venue_city', 'venue_state',
       'venue_postal_cd_sgmt_1', 'sales_platform_cd', 'print_flg',
       'la_valid_tkt_event_flg', 'fin_mkt_nm', 'gndr_cd', 'age_yr',
       'income_amt', 'edu_val', 'edu_1st_indv_val', 'edu_2nd_indv_val',
       'adults_in_hh_num', 'married_ind', 'child_present_ind',
       'home_owner_ind', 'occpn_val', 'occpn_1st_val', 'occpn_2nd_val',
       'dist_to_ven'],
      dtype='object')

Удаляем и объединяем смысловые дубликаты

In [ ]:
new_df.sample(4)

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
3192  e30292c82888137b32c0  12a60e4c409cf417e05a  ...           NaN         NaN
449   cc709ce9b04eb414fc3d  2957f6d687bcf99d7f8e  ...           NaN         NaN
4573  68a29910f68c56e31c96  f2aa1a2761fef9d53372  ...           NaN         NaN
136   1337f0e5b0c3e8bb52f7  6cdc2e270775b7e2f709  ...           NaN         NaN

[4 rows x 44 columns]

В большинстве случаев столбцы "event_disp_name" и "event_name" содержат одинаковые по смыслу записи.

In [ ]:
new_df.loc[4].event_name

'Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow'

In [ ]:
new_df.loc[4].event_disp_name

'Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow'

In [ ]:
new_df = new_df.drop('event_disp_name', axis=1)
new_df.sample(4)

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
3868  b4deb94e1332ecffdcd2  b165848bb56dffc8eb25  ...           NaN         NaN
424   9be4bf1006df1942bb66  4b677c3f5bec71eec8d1  ...           NaN         NaN
3651  cdf5bc3fcbe415adf1be  ac4b847b3fde66f2117e  ...           NaN         NaN
3208  e334eeeecb0c6bb6fe84  d769ab09a96be5a0b316  ...           NaN         NaN

[4 rows x 43 columns]

Аналогично столбцы "event_name",	"primary_act_name" и "secondary_act_name". В таких случаях я буду оставлять тот столбец, в котором больше всего информации.

In [ ]:
new_df = new_df.drop(['primary_act_name','secondary_act_name'], axis=1)
new_df.sample(4)

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
4332  cee88905fac807fc5f11  02fee4e221f610d8d7bd  ...           NaN         NaN
550   6501a8717b3dd96551af  3f510718b680022e6c39  ...           NaN         NaN
68    96d621fff678a4367095  34ad0e9254b8f7d1cbe0  ...           NaN         NaN
962   768a04d45f6368c8b027  c84bd97d323b0f7f3aa2  ...           NaN         NaN

[4 rows x 41 columns]

Объединю столбцы "venue_city" и "venue_state"

In [ ]:
new_df['venue_city/state'] = new_df['venue_city'].str.cat(df['venue_state'], sep =" / ")
new_df = new_df.drop(['venue_city','venue_state'], axis=1)
new_df.sample(4)

                  event_id  ...          venue_city/state
4777  f1a34af1a8fbdf777eb1  ...    INDIANAPOLIS / INDIANA
1534  2f8f5de0187b47c74f61  ...         ORLANDO / FLORIDA
1610  66fabcb22007056894fb  ...  CHULA VISTA / CALIFORNIA
269   9a2cb6e62509112a1169  ...       IRVINE / CALIFORNIA

[4 rows x 40 columns]

Приводим колонки к корректным типам данных.

In [ ]:
new_df = new_df.drop(['event_dt'], axis=1)

In [ ]:
new_df

                  event_id  ...             venue_city/state
1     abcaf1adb99a935fc661  ...    MANSFIELD / MASSACHUSETTS
2     6c56d7f08c95f2aa453c  ...          QUINCY / WASHINGTON
3     c7ab4524a121f9d687d2  ...            PHOENIX / ARIZONA
4     394cb493f893be9b9ed1  ...               DALLAS / TEXAS
5     55b5f67e618557929f48  ...          AUBURN / WASHINGTON
...                    ...  ...                          ...
4996  79372bc1e7e14dfd3f82  ...         HOLMDEL / NEW JERSEY
4997  f3b0de6a19e2a16e4fb1  ...     CHULA VISTA / CALIFORNIA
4998  7c9e2f6847a2dbe4ebff  ...       WHEATLAND / CALIFORNIA
4999  7af1ccd9a3ec3b6cef1c  ...  MARYLAND HEIGHTS / MISSOURI
5000  802f4bf8026e38c2acf2  ...           CHICAGO / ILLINOIS

[5000 rows x 39 columns]

Делим столбец sales_platform_cd на два: платформу и сайт.

In [ ]:
new_df.sales_platform_cd.unique()

array(['www.concerts.livenation.com', nan, 'www.livenation.com',
       'mobile.livenation.us', 'www.ticketmaster.com',
       'iphone.ticketmaster.us', 'android.ticketmaster.us',
       'iphone2.livenation.us', 'mobile.ticketmaster.us',
       'www.ticketmaster.ca', 'mobile.ticketmaster.ca',
       'androidphone2.livenation.us', 'iphone.ticketmaster.ca',
       'www.ticketmaster.com.mx'], dtype=object)

In [ ]:
sales_platform_cd_sep = new_df['sales_platform_cd'].str.split('.',expand=True)
sales_platform_cd_sep.columns=['platform','site','a','b']
sales_platform_cd_sep.sample(6)

     platform          site    a     b
4294      NaN           NaN  NaN   NaN
4073      NaN           NaN  NaN   NaN
3226      NaN           NaN  NaN   NaN
2218      www  ticketmaster  com  None
2317   mobile    livenation   us  None
4870      NaN           NaN  NaN   NaN

In [ ]:
sales_platform_cd_sep['site'] = sales_platform_cd_sep['site'].str.cat(sales_platform_cd_sep['a'], sep =".").str.cat(sales_platform_cd_sep['b'],sep=".")
sales_platform_cd_sep = sales_platform_cd_sep.drop(['a','b'], axis=1)
sales_platform_cd_sep

     platform                     site
1         www  concerts.livenation.com
2         NaN                      NaN
3         NaN                      NaN
4         NaN                      NaN
5         NaN                      NaN
...       ...                      ...
4996      NaN                      NaN
4997      www  concerts.livenation.com
4998      NaN                      NaN
4999      NaN                      NaN
5000      www                      NaN

[5000 rows x 2 columns]

In [ ]:
new_df = new_df.join(sales_platform_cd_sep)
new_df

                  event_id  ...                     site
1     abcaf1adb99a935fc661  ...  concerts.livenation.com
2     6c56d7f08c95f2aa453c  ...                      NaN
3     c7ab4524a121f9d687d2  ...                      NaN
4     394cb493f893be9b9ed1  ...                      NaN
5     55b5f67e618557929f48  ...                      NaN
...                    ...  ...                      ...
4996  79372bc1e7e14dfd3f82  ...                      NaN
4997  f3b0de6a19e2a16e4fb1  ...  concerts.livenation.com
4998  7c9e2f6847a2dbe4ebff  ...                      NaN
4999  7af1ccd9a3ec3b6cef1c  ...                      NaN
5000  802f4bf8026e38c2acf2  ...                      NaN

[5000 rows x 41 columns]

In [ ]:
new_df = new_df.drop(['sales_platform_cd'], axis=1)
new_df.head()

                event_id  ...                     site
10  93fce8094d89e0a94aac  ...                      NaN
12  6adcf8b2dc8a761b22b7  ...                      NaN
17  e6a1bc0620dc1fb45b6d  ...  concerts.livenation.com
27  dcc303578fdb9493de39  ...  concerts.livenation.com
30  b516196d16d9f600ed69  ...  concerts.livenation.com

[5 rows x 40 columns]

Оставляем только билеты на мероприятия.

In [ ]:
new_df.sample(4)

                  event_id  ...                     site
664   634067c8def7bc70e96f  ...  concerts.livenation.com
689   21bc22091d8e38544ee8  ...  concerts.livenation.com
2629  4dce3619cef24111da8a  ...                      NaN
2734  d15ffd25f35222823795  ...                      NaN

[4 rows x 41 columns]

In [ ]:
new_df = new_df.drop(new_df[new_df['major_cat_name']=='MISC'].index, axis=0)

In [ ]:
new_df = new_df.drop(new_df[new_df['la_event_type_cat']=='INVALID'].index, axis=0)

In [ ]:
new_df = new_df.drop(new_df[new_df['la_event_type_cat']=='PARKING'].index, axis=0)

In [ ]:
new_df = new_df.T.drop_duplicates().T
new_df.head()

                event_id  ...                     site
10  93fce8094d89e0a94aac  ...                      NaN
12  6adcf8b2dc8a761b22b7  ...                      NaN
17  e6a1bc0620dc1fb45b6d  ...  concerts.livenation.com
27  dcc303578fdb9493de39  ...  concerts.livenation.com
30  b516196d16d9f600ed69  ...  concerts.livenation.com

[5 rows x 26 columns]

In [ ]:
new_df.gndr_cd.unique()

In [ ]:
new_df = new_df.drop(['gndr_cd'], axis = 1)

In [ ]:
new_df[new_df['la_event_type_cat']=='UPSELL']

                  event_id        primary_act_id  ... platform site
340   45b205b19b3c1fc8473d  918a3a295ee63ea8ebc8  ...   iphone  NaN
982   2118e9e33242996a05a1  7b4045277eeee080a479  ...      www  NaN
1598  58ca3548002290887b7d  8b5d2ec892b056693313  ...      www  NaN
2113  964f2a8448f7c206ca28  c9fe81add330e8258ff5  ...      www  NaN
2361  f622310eaf168a038cbe  b6e0b2ef731574e25856  ...   mobile  NaN
2947  58ca3548002290887b7d  8b5d2ec892b056693313  ...      www  NaN
3089  628188b7363c3d340324  b6e0b2ef731574e25856  ...   iphone  NaN
3707  45b205b19b3c1fc8473d  918a3a295ee63ea8ebc8  ...   iphone  NaN
4435  491710c45352a1b06d09  0af71548579d986b7664  ...  android  NaN
4669  def87b25d0e0a85bcee1  44ab8d866e9091e7832a  ...      www  NaN

[10 rows x 26 columns]

Переименование столбцов

In [ ]:
new_df.columns

Index(['event_id', 'primary_act_id', 'secondary_act_id', 'purch_party_lkup_id',
       'event_name', 'major_cat_name', 'minor_cat_name', 'la_event_type_cat',
       'ticket_text', 'tickets_purchased_qty', 'trans_face_val_amt',
       'delivery_type_cd', 'event_date_time', 'presale_dt', 'onsale_dt',
       'sales_ord_create_dttm', 'sales_ord_tran_dt', 'print_dt', 'timezn_nm',
       'venue_postal_cd_sgmt_1', 'print_flg', 'la_valid_tkt_event_flg',
       'fin_mkt_nm', 'venue_city/state', 'platform', 'site'],
      dtype='object')

In [ ]:
new_df.la_event_type_cat.unique()

array(['CONCERTS', 'ARTS', 'UPSELL', 'SPORTS', 'FAMILY'], dtype=object)

In [ ]:
new_df.major_cat_name.unique()

In [ ]:
new_df.columns=['event_id', 'primary_act_id', 'secondary_act_id', 'purch_party_lkup_id',
       'event_name', 'event_type', 'event_subtype', 'la_event_type_cat',
       'ticket_text', 'tickets_purchased_quantity', 'price',
       'delivery_ticket_type', 'event_date_time', 'presale_date_time', 'onsale_date_time',
       'sales_ord_create_date_time', 'sales_ord_tran_date_time', 'print_date_time', 'timezone',
       'venue_postal_cd_sgmt_1', 'is_printed', 'is_valid_ticket_event',
       'purchase_location', 'venue_city/state', 'platform', 'site']

In [ ]:
new_df.sample(3)

                  event_id  ...                     site
3248  854b355f8320b9837d67  ...                      NaN
4911  ed185591acbb5012b1a4  ...                      NaN
551   53fe47432a44ae5ec1ca  ...  concerts.livenation.com

[3 rows x 26 columns]


1.  Какой наиболее популярный жанр концерта
2.  Сколько в среднем продается билетов за одну покупку
3.  Какой наиболее популярный сайт для покупки билетов

In [ ]:
new_df[new_df['event_type']=='CONCERTS'].groupby(['event_subtype']).count().event_id.sort_values(ascending=False)

event_subtype
ROCK/POP              720
ALTERNATIVE ROCK      401
COUNTRY               238
R & B                 128
RAP/URBAN             117
HEAVY METAL            90
COMEDY                 79
DANCE MUSIC/DANCE      60
LATIN MUSIC            43
ADULT CONTEMPORARY     17
ETHNIC/FOREIGN         17
POP                    12
FESTIVALS              12
FOLK                    9
TRIBUTE BAND            8
OTHER                   7
REGGAE                  7
GOSPEL                  7
PUNK                    6
SOUL                    4
OLDIES                  4
CLASSICAL/VOCAL         3
BLUES                   3
JAZZ                    1
CHANSON FRANCAISE       1
BLUEGRASS               1
Name: event_id, dtype: int64

In [ ]:
new_df['tickets_purchased_quantity'].mean()

2.2977777777777777

In [ ]:
new_df.groupby(['site']).count().event_id.sort_values(ascending=False)

site
concerts.livenation.com    646
ticketmaster.com.mx          1
Name: event_id, dtype: int64